// Generates src/tokens.css and the front matter of DESIGN.md from design/visual/tokens.json,
// so the approved colors have one source. With --check, fails when either file is out of date.
import { readFileSync, writeFileSync } from "node:fs";

const tokens = JSON.parse(readFileSync("design/visual/tokens.json", "utf8"));
const games = ["genshin", "hsr", "zzz"];

// shadcn/ui variable names, mapped onto the visual direction's roles.
function themeVariables(theme) {
  return {
    background: theme.bg,
    foreground: theme.text,
    card: theme.surface,
    "card-foreground": theme.text,
    popover: theme.surface,
    "popover-foreground": theme.text,
    // A hover and selected fill that shows on the window and on panels.
    muted: theme.hairline,
    "muted-foreground": theme.muted,
    secondary: theme.bg,
    "secondary-foreground": theme.text,
    border: theme.hairline,
    input: theme.control,
    warning: theme.warning,
    destructive: theme.warning,
    ...Object.fromEntries(
      games.flatMap((game) => {
        const a = theme.accent[game];
        return [
          [game, a.base],
          [`${game}-on`, a.on],
          [`${game}-soft`, a.soft],
          [`${game}-text`, a.text],
        ];
      }),
    ),
  };
}

const declarations = (vars, indent) =>
  Object.entries(vars)
    .map(([name, value]) => `${indent}--${name}: ${value};`)
    .join("\n");

// The selected game sets the accent for the whole window (data-game on <html>).
const accent = (game) => ({
  primary: `var(--${game})`,
  "primary-foreground": `var(--${game}-on)`,
  accent: `var(--${game}-soft)`,
  "accent-foreground": `var(--${game}-text)`,
  ring: `var(--${game})`,
});

const css = `/* Generated by scripts/tokens.mjs from design/visual/tokens.json. Do not edit. */
:root {
  color-scheme: light dark;
${declarations(themeVariables(tokens.light), "  ")}
  --radius: ${tokens.shape.radiusControl};
  --radius-cell: ${tokens.shape.radiusCell};
  --radius-checkbox: ${tokens.shape.radiusCheckbox};
  --focus-ring: ${tokens.shape.focusRing};
  --font-text: "${tokens.font.text}", Pretendard, "Malgun Gothic", "Segoe UI", sans-serif;
  --font-code: "${tokens.font.code}", Consolas, monospace;
${declarations(accent(games[0]), "  ")}
}

@media (prefers-color-scheme: dark) {
  :root {
${declarations(themeVariables(tokens.dark), "    ")}
  }
}
${games.map((game) => `\n:root[data-game="${game}"] {\n${declarations(accent(game), "  ")}\n}\n`).join("")}`;

function yamlColors(theme) {
  return Object.entries(themeVariables(theme))
    .map(([name, value]) => `    ${name}: "${value}"`)
    .join("\n");
}

const frontMatter = `---
# Generated by scripts/tokens.mjs from design/visual/tokens.json. Edit the tokens, then run pnpm tokens.
name: 4GHz
description: "Schedules, redeem codes, and a chore calendar for Genshin Impact, Honkai: Star Rail, and Zenless Zone Zero."
colors:
  light:
${yamlColors(tokens.light)}
  dark:
${yamlColors(tokens.dark)}
typography:
  text: "${tokens.font.text}"
  code: "${tokens.font.code}"
rounded:
  control: "${tokens.shape.radiusControl}"
  cell: "${tokens.shape.radiusCell}"
  checkbox: "${tokens.shape.radiusCheckbox}"
focusRing: "${tokens.shape.focusRing}"
---
`;

const design = readFileSync("DESIGN.md", "utf8")
  .replace(/^\uFEFF/, "")
  .replace(/\r\n/g, "\n");
const frontMatterPattern = /^---\n(?:[\s\S]*?\n)?---\n/;
if (!frontMatterPattern.test(design))
  throw new Error("DESIGN.md must start with a --- front matter block");
const body = design.replace(frontMatterPattern, "");
const outputs = { "src/tokens.css": css, "DESIGN.md": frontMatter + body };

if (process.argv.includes("--check")) {
  const stale = Object.entries(outputs).filter(
    ([file, text]) => readFileSync(file, "utf8") !== text,
  );
  if (stale.length > 0) {
    console.error(
      `Out of date with tokens.json: ${stale.map(([file]) => file).join(", ")}. Run pnpm tokens.`,
    );
    process.exit(1);
  }
  console.log("Design tokens: generated files are up to date.");
} else {
  for (const [file, text] of Object.entries(outputs)) writeFileSync(file, text);
  console.log("Wrote src/tokens.css and the DESIGN.md front matter.");
}
